<a href="https://colab.research.google.com/github/VrdnAlex/goit-ds-hw-01/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 1. Створіть одновимірний масив з першими 10-ма натуральними числами та виведіть його значення.
vector1 = np.arange(1, 11)
print("1. Одновимірний масив з першими 10-ма натуральними числами:")
print(vector1)

# 2. Створіть двовимірний масив розміром 3x3, заповніть його нулями та виведіть його значення.
matrix1 = np.zeros((3, 3))
print("\n2. Двовимірний масив 3x3, заповнений нулями:")
print(matrix1)

# 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
matrix2 = np.random.randint(1, 11, (5, 5))
print("\n3. Масив 5x5, заповнений випадковими цілими числами від 1 до 10:")
print(matrix2)

# 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
matrix3 = np.random.rand(4, 4)
print("\n4. Масив 4x4, заповнений випадковими дійсними числами від 0 до 1:")
print(matrix3)

# 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
vector2 = np.random.randint(1, 11, 5)
vector3 = np.random.randint(1, 11, 5)
print("\n5. Два одновимірні масиви розміром 5, заповнені випадковими цілими числами від 1 до 10:")
print("Вектор 1:", vector2)
print("Вектор 2:", vector3)
print("Поелементне додавання:", vector2 + vector3)
print("Поелементне віднімання:", vector2 - vector3)
print("Поелементне множення:", vector2 * vector3)

# 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
vector4 = np.random.rand(7)
vector5 = np.random.rand(7)
scalar_product = np.dot(vector4, vector5)
print("\n6. Два вектори розміром 7, заповнені довільними числами, та їх скалярний добуток:")
print("Вектор 1:", vector4)
print("Вектор 2:", vector5)
print("Скалярний добуток:", scalar_product)

# 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
matrix4 = np.random.randint(1, 11, (2, 2))
matrix5 = np.random.randint(1, 11, (2, 3))
matrix_product = np.dot(matrix4, matrix5)
print("\n7. Дві матриці (2x2 та 2x3), заповнені випадковими цілими числами від 1 до 10, та їх добуток:")
print("Матриця 1 (2x2):")
print(matrix4)
print("Матриця 2 (2x3):")
print(matrix5)
print("Добуток матриць:")
print(matrix_product)

# 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
matrix6 = np.random.randint(1, 11, (3, 3))
inverse_matrix = np.linalg.inv(matrix6)
print("\n8. Матриця 3x3, заповнена випадковими цілими числами від 1 до 10, та її обернена матриця:")
print("Матриця:")
print(matrix6)
print("Обернена матриця:")
print(inverse_matrix)

# 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
matrix7 = np.random.rand(4, 4)
transposed_matrix = np.transpose(matrix7)
print("\n9. Матриця 4x4, заповнена випадковими дійсними числами від 0 до 1, та її транспонована матриця:")
print("Матриця:")
print(matrix7)
print("Транспонована матриця:")
print(transposed_matrix)

# 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
matrix8 = np.random.randint(1, 11, (3, 4))
vector6 = np.random.randint(1, 11, 4)
matrix_vector_product1 = np.dot(matrix8, vector6)
print("\n10. Матриця 3x4 та вектор розміром 4, заповнені випадковими цілими числами від 1 до 10, та їх добуток:")
print("Матриця:")
print(matrix8)
print("Вектор:")
print(vector6)
print("Добуток матриці на вектор:")
print(matrix_vector_product1)

# 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
matrix9 = np.random.rand(2, 3)
vector7 = np.random.rand(3)
matrix_vector_product2 = np.dot(matrix9, vector7)
print("\n11. Матриця 2x3 та вектор розміром 3, заповнені випадковими дійсними числами від 0 до 1, та їх добуток:")
print("Матриця:")
print(matrix9)
print("Вектор:")
print(vector7)
print("Добуток матриці на вектор:")
print(matrix_vector_product2)

# 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
matrix10 = np.random.randint(1, 11, (2, 2))
matrix11 = np.random.randint(1, 11, (2, 2))
elementwise_product = matrix10 * matrix11
print("\n12. Дві матриці 2x2, заповнені випадковими цілими числами від 1 до 10, та їхнє поелементне множення:")
print("Матриця 1:")
print(matrix10)
print("Матриця 2:")
print(matrix11)
print("Поелементне множення:")
print(elementwise_product)

# 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
matrix12 = np.random.randint(1, 11, (2, 2))
matrix13 = np.random.randint(1, 11, (2, 2))
matrix_product2 = np.dot(matrix12, matrix13)
print("\n13. Дві матриці 2x2, заповнені випадковими цілими числами від 1 до 10, та їх добуток:")
print("Матриця 1:")
print(matrix12)
print("Матриця 2:")
print(matrix13)
print("Добуток матриць:")
print(matrix_product2)

# 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
matrix14 = np.random.randint(1, 101, (5, 5))
sum_elements = np.sum(matrix14)
print("\n14. Матриця 5x5, заповнена випадковими цілими числами від 1 до 100, та сума її елементів:")
print("Матриця:")
print(matrix14)
print("Сума елементів матриці:", sum_elements)

# 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
matrix15 = np.random.randint(1, 11, (4, 4))
matrix16 = np.random.randint(1, 11, (4, 4))
matrix_difference = matrix15 - matrix16
print("\n15. Дві матриці 4x4, заповнені випадковими цілими числами від 1 до 10, та їхня різниця:")
print("Матриця 1:")
print(matrix15)
print("Матриця 2:")
print(matrix16)
print("Різниця матриць:")
print(matrix_difference)

# 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
matrix17 = np.random.rand(3, 3)
row_sums = np.sum(matrix17, axis=1)
print("\n16. Матриця 3x3, заповнена випадковими дійсними числами від 0 до 1, та вектор-стовпчик з сумами елементів кожного рядка:")
print("Матриця:")
print(matrix17)
print("Вектор-стовпчик (суми рядків):")
print(row_sums)

# 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
matrix18 = np.random.randint(1, 11, (3, 4))
squared_matrix = matrix18 ** 2
print("\n17. Матриця 3x4 з довільними цілими числами та матриця з квадратами цих чисел:")
print("Матриця:")
print(matrix18)
print("Матриця з квадратами чисел:")
print(squared_matrix)

# 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
vector8 = np.random.randint(1, 51, 4)
sqrt_vector = np.sqrt(vector8)
print("\n18. Вектор розміром 4, заповнений випадковими цілими числами від 1 до 50, та вектор з квадратними коренями цих чисел:")
print("Вектор:")
print(vector8)
print("Вектор з квадратними коренями чисел:")
print(sqrt_vector)

1. Одновимірний масив з першими 10-ма натуральними числами:
[ 1  2  3  4  5  6  7  8  9 10]

2. Двовимірний масив 3x3, заповнений нулями:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

3. Масив 5x5, заповнений випадковими цілими числами від 1 до 10:
[[ 3  4  4  7 10]
 [ 5  4  5  5  9]
 [ 9  6  1 10 10]
 [ 1  9  4 10  3]
 [ 5  6  9  6  2]]

4. Масив 4x4, заповнений випадковими дійсними числами від 0 до 1:
[[0.15908809 0.16622663 0.35671644 0.93298807]
 [0.1981526  0.66780536 0.97357806 0.53010571]
 [0.05583491 0.79375276 0.76947271 0.2688245 ]
 [0.28291738 0.5138688  0.95127522 0.60533761]]

5. Два одновимірні масиви розміром 5, заповнені випадковими цілими числами від 1 до 10:
Вектор 1: [2 6 3 1 1]
Вектор 2: [10 10 10 10  1]
Поелементне додавання: [12 16 13 11  2]
Поелементне віднімання: [-8 -4 -7 -9  0]
Поелементне множення: [20 60 30 10  1]

6. Два вектори розміром 7, заповнені довільними числами, та їх скалярний добуток:
Вектор 1: [0.27638614 0.27419826 0.96973379 0.4024704  0.08971276 0.985